create table task (
    id bigint generated by default as identity, 
    description varchar(255), 
    score integer not null check (score>=1), 
    status integer not null, 
    title varchar(255), 
    primary key (id)
);


Insert into Task(title, description, score, status)
    Values ('Modelar BD', 'modelar as tabelas', 150, 0);